FROM golang:1.22-alpine AS builder

RUN apk add --no-cache gcc musl-dev

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o main ./cmd

FROM alpine:latest
    
WORKDIR /app
COPY --from=builder /app/main .
    
EXPOSE 8080
    
CMD ["./main"]
    


# //ARM Architecture

# FROM golang:1.20-alpine AS builder

# RUN apk add --no-cache gcc musl-dev

# WORKDIR /app

# COPY go.mod go.sum ./

# RUN go mod download

# COPY . .

# RUN GOARCH=arm64 GOOS=linux go build -o main ./cmd

# FROM alpine:latest

# WORKDIR /app

# COPY --from=builder /app/main .

# COPY --from=builder /app/mail/templates mail/templates

# EXPOSE 8080

# CMD ["./main"]